apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: liberu-crm

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- pvc.yaml
- resource-quota.yaml
- mysql-statefulset.yaml
- redis.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- network-policy.yaml

commonLabels:
  app: liberu-crm
