apiVersion: v1
kind: Service
metadata:
  name: liberu-crm
  namespace: liberu-crm
  labels:
    app: liberu-crm
    component: application
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: liberu-crm
    component: application
